config/routes.rb
AnnotationStudio::Application.routes.draw do
  use_doorkeeper

  get "public/:id" => "public_documents#show"
  get "review/:id" => "public_documents#show"

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks",
                                    sessions: "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :documents do
    resources :annotations
    post :set_default_state
    post :publish
    post :publicize
    post :archive
    post :snapshot
    get :export
  end

  resources :users, only: [:show, :edit]

  authenticated :user do
    root :to => "users#show"
    get "dashboard", to: "users#show", as: :dashboard

    post "annotations", to: "annotations#search"
    get "annotations", to: "annotations#index"
    get "annotations/:id", to: "annotations#show"
    get "documents/:document_id/annotations/field/:field", to: "annotations#field"
    get "leave" => "groups#leave"

    #post 'join_via_name' => "groups#join_via_name" #for joining new groups via name entry

    resources :groups

    #should they be post instead?
    get "remove_member", to: "groups#remove_member"
    post "update_member_role", to: "groups#update_member_role"

    resources :invites

    get "toggleIS", to: "groups#toggleIS"
    post "toggleIS", to: "groups#toggleIS"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"

      #invite link for unauthenticated user
      get "/dashboard" => "devise/sessions#new"
    end
  end

  get "exception_test" => "annotations#exception_test"
  # root :to => "devise/sessions#new"

  namespace :api do
    namespace :v1 do
      # api routes
      get "/me" => "credentials#me"
      get "/my_groups" => "credentials#my_groups"
      get "/group_members" => "credentials#group_members"
      post "/docmeta" => "docmeta#docmeta"
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :memberships, :foreign_key => "group_id"
	has_many :users, through: :memberships
	accepts_nested_attributes_for :memberships

	has_and_belongs_to_many :documents

	has_many :invites
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

  def show
    @group = Group.find(params[:id])
    @memberships = @group.memberships
    @documents = @group.documents
  end

  # GET /groups/new
  # GET /groups/new.xml
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render xml: @group }
    end
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      @group.users << current_user

      #set role to owner
      Membership.find_by(group_id: @group.id, user_id: current_user.id).update_attribute("role", "owner")

      flash[:success] = "Created Group " + @group.name + " successfully!"
      redirect_to edit_group_path(id: @group.id)
    else
      flash[:alert] = "Error in creating group."
      redirect_to request.referrer
    end
  end

  def edit
    @group = Group.find(params[:id])
    if params["search"] #group member search
      queryStr = "%" + params["search"].downcase + "%"
      matches = User.where(["lower(users.firstname) LIKE ?", queryStr]).pluck(:id)
      @memberships = Membership.includes(:user).where(group_id: params[:id], user_id: matches)
    else
      @memberships = @group.memberships
    end

    @ISstatus = @group.ideaSpaceOn ? "Enabled" : "Disabled" #whether Idea space is enabled or disabled
    @IStoggle = @group.ideaSpaceOn ? "Disable" : "Enable" #toggle button
  end

  def update
    @group_id = params["id"]
    @group = Group.find(@group_id)

    if params["email"]
      new_email = params["email"]
      user = User.find_by(email: new_email)
      if user && (!user.groups.include? @group)
        @group.users << user
        flash[:success] = user.fullname + " added."
        # InviteMailer.notify_existing_user(user, @group).deliver_now
      else
        flash[:alert] = "User not found or already in group."
      end
    end
    if params["name"] && params["commit"] == "Save"
      if params["name"] == ""
        flash[:alert] = "Group name cannot be blank."
      else
        @group.name = params["name"]
        if @group.save
          flash[:success] = "Group name changed to \"" + params["name"] + "\" successfully."
        else
          flash[:alert] = "Error changing Group name."
        end
      end
    end
    redirect_to request.referrer
  end

  def destroy
    @group_id = params["id"]
    @group = Group.find(@group_id)
    if @group.destroy
      flash[:success] = "Group " + @group.name.to_s + " was deleted."
    else
      flash[:alert] = "Error deleting group " + @group.name.to_s + "."
    end
    redirect_to groups_path
  end



  def update_member_role
    @membership = Membership.find(params[:m_id])
    if @membership.update_attribute("role", params[:role])
      flash[:success] = "Changed  " + params[:username] + "'s role to " + params[:role]
    else
      flash[:alert] = "Error changing " + params[:username] + "'s role to " + params[:role]
    end

    redirect_to edit_group_path(id: params[:group_id])
  end

  def leave
    @gid = params[:id]
    @uid = current_user.id
    @membership = Membership.find_by(user_id: @uid, group_id: @gid)

    if @membership
      @membership.destroy
      flash[:success] = "Left " + Group.find(@gid).name.to_s
    else
      flash[:alert] = "Error leaving group"
    end

    respond_to do |format|
      format.html { redirect_to dashboard_path(nav: "mygroups") }
      format.xml { head :no_content }
    end
  end

  def remove_member
    @membership = Membership.find(params[:m_id])
    if @membership
      @membership.destroy
      flash[:success] = "Removed " + params[:username]
    else
      flash[:alert] = "Error removing member"
    end

    redirect_to request.referrer
  end

  def toggleIS
    thisGroup = Group.find(params[:group_id])
    if params[:ideaSpace] == "change"
      current = thisGroup.ideaSpaceOn
      state = !current ? "on" : "off"
      if thisGroup.update_attribute("ideaSpaceOn", !current) #toggle between true and false
        flash[:success] = "Turned Idea Space " + state
      else
        flash[:alert] = "Error turning Idea Space " + state
      end
      redirect_to edit_group_path(id: params[:group_id])
    end
  end

  def bad_permissions
    flash[:alert] = "You do not have permission to manage " + @group.name.to_s + "."
    redirect_to groups_path
  end
  helper_method :bad_permissions

  private

  def group_params
    params.require(:group).permit(:name, :owner_id)
  end
end

app/views/groups/_leftnav.html.erb
<!-- groups/_leftnav.html.erb -->

app/views/groups/_permissions.html.erb
<!-- groups/_permissions.html.erb -->

  <div class="panel panel-default" id="permissions-panel">
    <div class="panel-heading">
      <span class="panel-title">Group role permissions explained</span>
    </div>
    <ul class="list-group">
      <li class="list-group-item"><b>Members</b>: Group Members can see documents and annotations shared with the group, and can annotate those documents. They can also see who else is in the group.</li>
      <li class="list-group-item"><b>Managers</b>: Group Managers are Members who can also invite users to the group, remove users from the group, and change users' roles between Manager and Member.</li>
      <li class="list-group-item"><b>Owners</b>: Group Owners are Managers who can also delete the group.</li>
    </ul>
  </div>

app/views/groups/_rightnav.html.erb
<!-- groups/_rightnav.html.erb -->
<ul class="nav navmenu-nav" id="usernav">
  <li><a href="http://support.annotationstudio.org/" target="_blank">Help <i class="fa fa-external-link-square"></i></a></li>
</ul>

app/views/groups/edit.html.erb
<%= content_for :page_title, "Manage Group: #{@group.name}" %>
<%= content_for :body_id, 'groups' %>
<%= content_for :body_class, 'edit' %>
<%= stylesheet_link_tag "groups" %>
<% if is_owner(params[:id]) or is_manager(params[:id]) %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= form_for @group do |f| %>
        <%= f.hidden_field :group_id, :value => params[:id] %>
        <%= f.label :name, {:class=>"panel-title"} do %>
          <%= text_field_tag 'name', @group.name, size: @group.name.length+5, class: 'editable-title' %><a id="edit-title-btn"><i class="fa fa-pencil panel-title"></i> </a>
        <% end %>
        <%= f.submit :Save, {:class=>'btn btn-success btn-sm editing-title-btns'} %>
        <%= f.submit 'Cancel', :type => "reset", :class=>'btn btn-default btn-sm editing-title-btns', :id=>"edit-title-cancel" %>
      <% end %>
      <a class="btn btn-default btn-sm" id="group-management-tour"><i class="fa fa-info-circle"></i> &nbsp;How to use this page</a>
    </div>
    <!-- / .panel-heading -->
    <div class="panel-body">
      <div class="col-md-6" id="table-col">
        <div class="form-group">
          <input id="first-name-search" placeholder="Search for a member by name" class="form-control" type="text">
        </div>
        <table id="names-table" class="table table-striped table-bordered">
          <tr>
            <th> Name </th>
            <th> Role </th>
            <% if is_owner(params[:id]) or is_manager(params[:id]) %>
              <th> Actions </th>
            <% end #if.is_owner %>
          </tr>
          <% if !@memberships.empty? %>
            <% @memberships.each do |m| %>
              <tr>
                <% @user = User.find(m.user_id) %>
                <td> <!-- doesn't error check for missing last name -->
                  <%= @user.fullname %>
                </td>
                <td>
                  <% case m.role %>
                  <% when 'owner' %>
                    <span class="label label-primary"><%= m.role %> </span>
                  <% when 'member' %>
                    <%= form_tag :controller=>'groups', :action => 'update_member_role', :method => :post, :m_id=>m.id,:username => @user.fullname do %>
                      <%= select_tag :role, options_for_select([ "member", "manager" ], "member"), {onchange: "this.form.submit();"} %>
                      <%= hidden_field_tag :group_id, params[:id] %>
                    <% end %>
                  <% when 'manager' %>
                    <%= form_tag :controller=>'groups', :action => 'update_member_role', :method => :post, :m_id=>m.id,:username => @user.fullname do %>
                      <%= select_tag :role, options_for_select([ "member", "manager" ], "manager"), {onchange: "this.form.submit();"} %>
                      <%= hidden_field_tag :group_id, params[:id] %>
                    <% end %>
                  <% else %>
                    <span class="label label-default"><%= m.role %> </span>
                  <% end %>

                </td>
                <% if is_owner(params[:id]) or is_manager(params[:id]) %>
                  <td>
                    <% unless m.role == "owner" %>
                      <%= link_to remove_member_path({:m_id => m.id, :username => @user.fullname}), {:class => 'btn btn-danger btn-sm', data: {confirm: "Are you sure you want to remove this member?", toggle: 'tooltip', placement: 'top', original_title: 'Remove'}} do %>
                        <i class="glyphicon glyphicon-remove" title="Remove"></i> Remove
                      <% end %>
                    <% end %>
                  </td>
                <% end %> <!-- end if -->
              </tr>
            <% end %> <!-- end loop -->
          <% end %> <!-- end if -->
        </table>
      </div>
      <% optionsCol = is_owner(params[:id]) ? "3" : "6" %>
      <div class="col-md-<%= optionsCol %>" id="options-col">
        <% @i = Invite.find_by(group_id: params[:id]) %>
        <% if @i && params[:destroy_invite] == "true" %>
          <% if @i.destroy %>
            <% flash[:notice] = "Invite link successfully removed." %>
          <% else %>
            <% flash[:notice] = "Invite link removal failed." %>
          <% end %>
        <% end %>
        <% if @i && (@i.expiration_date.nil? || @i.expiration_date > Time.now) && params[:destroy_invite] != "true" %>
          <h5><%= label_tag 'Invite Link' %></h5>
          <p>Send this link to registered or new users. (If the link is not working, you can <a href="<%= edit_group_path(@group.id, :destroy_invite=>'true') %>">click here to remove it</a> and generate a new one. The old link will no longer work.)</p>
          <div class="input-group">
            <%= text_field_tag "Generate Invite Link:", request.base_url + new_user_registration_path(:invite_token => @i.token).to_s, {:size =>40, :class => 'form-control', :id=>"invite-link"} %>
            <span class="input-group-btn">
              <%= button_tag 'Copy', {:class=>'btn btn-default',:id=> 'copy-button'} %>
            </span>
          </div>
        <% else %>
          <% if @i %>
            <% @i.destroy %>
          <% end %>
          <%= form_for Invite.new , :url => invites_path do |f| %>
            <%= f.hidden_field :group_id, :value => params[:id] %>
            <h5><%= f.label 'Invite Link' %></h5>
            <p>Generate an invite link to send to registered or new users.</p>
            <div class="input-group">
              <%= f.submit 'Generate',:class=>'btn btn-default' %>
            </div>
          <% end #form_for %>
        <% end #if @i %>
        <h5><%= label_tag 'Add registered user' %></h5>
        <p>Automatically add a registered user to this group by entering their email here.</p>
        <%= form_for @group do |f| %>
          <div class="input-group">
            <%= email_field_tag :email, params['search'], :placeholder=> 'User\'s email', :class=>"form-control" %>
            <span class="input-group-btn">
              <%= f.submit :Add,:class=>'btn btn-default' %>
            </span>
          </div>
        <% end %> <!-- form_for -->
      </div>
      <div class="col-md-3" id="delete-col">
        <% if ENV["GLOBAL_IDEA_SPACE"] == "true"  && is_owner(params[:id]) %>
          <%= form_tag :controller=>'groups', :action => 'toggleIS' do %>
            <h5><%= label_tag :toggleIS, 'Idea Space: ' + @ISstatus %></h5>
            <p>Enable or disable Idea Space for this group.</p>
            <%= hidden_field_tag :ideaSpace, 'change' %>
            <%= hidden_field_tag :group_id, params[:id] %>
            <%= submit_tag @IStoggle, :class=>'btn btn-default' %>
          <% end %>
        <% end %>
        <% if is_owner(params[:id]) %>
          <h5><%= label_tag 'Delete Group' %></h5>
          <p>Delete this group permanently. This action cannot be undone. <br />Documents assigned to this group will not be deleted, but may become inaccessible to group members.</p>
          <%= link_to group_path(@group), data: {:confirm => "Are you sure?"}, :method => :delete, :class=>'btn btn-danger' do %>
            <i class="glyphicon glyphicon-trash" title="Delete"></i> Delete Group
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- forms -->
  </div>
  <%= render "groups/permissions" %>

  <script type="text/javascript">
    //for invite link copy to clipboard
    //source: https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
    var copyButton = document.getElementById('copy-button');
    if (copyButton != undefined){
    copyButton.addEventListener('click', function (event) {
      var copyLink = document.querySelector('#invite-link');
      copyLink.focus();
      copyLink.select();
      try {
        var successful = document.execCommand('copy');
        var msg = successful ? 'successful' : 'unsuccessful';
        console.log(msg);
      } catch (err) {
        console.log('unable to copy')
      }
    });
    }
    
    // Case-insensitive contains method, source: https://jsfiddle.net/bipen/dyfRa/
    $.extend($.expr[":"], {
    "containsIN": function(elem, i, match, array) {
    return (elem.textContent || elem.innerText || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
    }
    });
    
    // Jquery filter, source: https://stackoverflow.com/a/17075148/394067
    $("#first-name-search").keyup(function () {
    //split the current value of searchInput
    var data = this.value.split(" ");
    //create a jquery object of the rows
    var nameTable = $("#names-table").find("tr:not(:first)");
    if (this.value == "") {
      nameTable.show();
      return;
    }
    nameTable.hide();
    nameTable.filter(function (i, v) {
      var $t = $(this);
      for (var d = 0; d < data.length; ++d) {
        if (!$t.find("td:first-of-type").is(":containsIN('" + data[d] + "')") || $t.is("tr:first-of-type")) {
          return false;
        }
      }
      return true;
    })
      .show();
    }).focus(function () {
      this.value = "";
      $(this).unbind('focus');
    });
    
    // Copying and tooltip
    var inviteLink = document.getElementById("invite-link");
    if(inviteLink != undefined){
      inviteLink.onclick = function() {
        this.select();
        document.execCommand('copy');
      }
    }
    $('#invite-link').tooltip({'trigger':'focus', 'title': 'Link copied!' });
   
    function startGroupManagementTour() {
      var intro = introJs();
      intro.setOptions({
        doneLabel: 'Done',
        skipLabel: 'Exit tour',
        disableInteraction: true,
        showBullets: false,
        showStepNumbers: false,
        scrollToElement: false,
        exitOnOverlayClick: true,
        steps: [
          {
            element: '.panel',
            intro: "This is the Management page for the Group \"<%= @group.name.truncate(50) %>\"."
          },
          {
            element: '#name',
            intro: "The Group can be renamed by clicking in the editable area here."
          },
          {
            element: '#table-col',
            intro: "On the left is a table showing all Group members and their roles. This table can be quickly filtered with the search box."
          },
          {
            element: '#table-col',
            intro: "Here, Managers and Owners can remove people from the Group, as well as make changes to their roles. (Owners cannot be removed or change roles.)"
          },
          <% if is_manager(params[:id]) %>
          {
            element: '#table-col',
            intro: "If you are a Manager and not an Owner, be careful! It is possible to change your own role or remove yourself from the group."
          },
          <% end %>
          {
            element: '#options-col',
            intro: "Here are two options for adding Members to your Group."
          },
          {
            element: '#options-col',
            intro: "The first option allows you to generate an invite link to send to anyone. If you give someone this link who has not signed up for Annotation Studio, they will automatically be added to the group on signup."
          },
          {
            element: '#options-col',
            intro: "The second option allows you to quickly add people to your Group who have already signed up for Annotation Studio. Just enter their email and they will be automatically added."
          },
          <% if is_owner(params[:id]) %>
            {
              element: '#delete-col',
              intro: "Since you are an Owner, you can delete this group. (Managers cannot delete the Group.)"
            },
          <% end %>
            {
              intro: "This concludes the Annotation Studio Groups tour. If something is wrong or broken, or you need more help, please do not hesitate to contact us at <a href=\"mailto:annotationstudio-support@mit.edu\">annotationstudio-support@mit.edu</a>."
            }
        ]
      });
      intro.start();
    }

    if("<%= params[:tour] %>" == "true"){
      startGroupManagementTour();
    }

    $('#group-management-tour').click(startGroupManagementTour);

    function editTitle(){
      $('#name').attr("class","form-control form-control-inline editing-title");
      $('#name').focus();
      $('.editing-title-btns').show();
      $('#edit-title-btn').hide();
      $('.edit_group').addClass("editing-group");
    }

    $('.editing-title-btns').hide();
    $('#name').click(editTitle);
    $('#edit-title-btn').click(editTitle);
    $('#edit-title-cancel').click(function(){
      $('.editing-title-btns').hide();
      $('#edit-title-btn').show();
      $('#name').attr("class", "editable-title");
      $('#name').html("<%= @group.name %>");
      $('.edit_group').removeClass("editing-group");
    })

  </script>
<% else %>
  <% bad_permissions %>
<% end %>

app/views/groups/index.html.erb
<%= content_for :page_title, 'Groups' %>
<%= content_for :body_id, 'groups' %>
<%= content_for :body_class, 'index' %>
<%= stylesheet_link_tag "groups" %>
<div class="panel panel-default" id="groups-panel">
  <div class="panel-heading">
    <span class="panel-title">Groups</span>
  </div>
  <!-- / .panel-heading -->
  <div class="tab-content">
    <div class="tab-pane no-padding active" id="all">
      <table class="table table-striped table-bordered">
        <tr>
          <th>Group Name</th>
          <th>Role</th>
          <th>Owner</th>
          <th>Members</th>
          <th id="button-column">Actions</th>
        </tr>
        <% @groups.each do |g| %>
          <tr>
            <td><%= link_to g.name, group_path(id: g.id) %> </td>
            <% myRole = Membership.find_by(group_id: g.id, user_id: current_user.id).role %>
            <td>
              <% case myRole %>
              <% when 'owner' %>
              <% labelcolor = 'label-primary' %>
              <% when 'manager' %>
              <% labelcolor = 'label-warning' %>
            <% else %>
              <% labelcolor = 'label-default' %>
            <% end %>
            <span class="label <%= labelcolor %>"><%= myRole %> </span>
          </td>
          <td><%= User.find(g.owner_id).first_name_last_initial %> </td>
          <% m = Membership.where(group_id: g.id) %>
          <td><%= m.size %></td>
          <td>
            <% if myRole == "owner" or myRole == "manager" %>
              <%= link_to edit_group_path(id: g.id) , :class => 'btn btn-default btn-sm' do %>
                <i class="glyphicon glyphicon-pencil" title="Edit"></i> Manage
              <% end %>
            <%end%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<div class="panel-footer doc-set-footer">
  <% if can? :create, Group %>
    <%= link_to group_path('new'), class: 'btn btn-primary create-new-button' do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Create New Group
    <% end %>
  <% end %>
</div>
</div>
<!--/.panel-->
<%= render "groups/permissions" %>

<script type="text/javascript">

  function startGroupsIndexTour() {

    <% managedGroupId = -1 %>
    <% managedGroupNum = 0 %>
    <% if !@groups.empty? %>
      <% @groups.each do |g| %>
        <% managedGroupNum += 1 %>
        <% if g.owner_id == current_user.id or is_manager(g.id) %>
          <% managedGroupId = g.id.to_i %>
          <% break %>
        <% end %>
      <% end %>
    <% end %>

    var intro = introJs();
    intro.setOptions({
      doneLabel: 'OK',
      skipLabel: 'Exit tour',
      disableInteraction: true,
      showBullets: false,
      showStepNumbers: false,
      scrollToElement: false,
      exitOnOverlayClick: true,
      steps: [
        {
          element: '#groups-panel',
          intro: "This is the Groups overview page."
        },
        {
          element: '#groups-panel .tab-content',
          intro: "This overview tells you things about all of your Groups, including your role, the owner's name, and the number of members."
        },
        {
          element: '#permissions-panel',
          intro: "Below is a helpful cheatsheet to explain what each role means."
        },
        <% if managedGroupId == -1 %>
          {
            element: '#groups-panel .tab-content .tab-pane table tbody tr:nth-of-type(2) td:first-of-type',
            intro: "Let's navigate to this Group's detail view."
          }
        <% else %>
          {
            element: '#groups-panel .tab-content .tab-pane table tbody tr:nth-of-type(<%= (managedGroupNum+1).to_s %>) td:first-of-type',
            intro: "Let's navigate to this Group's detail view."
          }
        <% end %>
      ]
    });
    intro.start().oncomplete(function() {
      <% if !@groups.empty? %>
        <% if managedGroupId == -1 %>
          window.location.href = "<%= group_path(id: @groups[0].id, tour: 'true') %>";
        <% else %>
          window.location.href = "<%= group_path(id: managedGroupId, tour: 'true') %>";
        <% end %>
      <% end %>
    });
  }
  if("<%= params[:tour] %>" == "true"){
    startGroupsIndexTour();
  }
</script>

app/views/groups/new.html.erb
<%= content_for :page_title, 'New Group' %>
<%= content_for :body_id, 'groups' %>
<%= content_for :body_class, 'new' %>
<div class="panel panel-default">
  <div class="panel-heading"><span class="panel-title">Create a New Group</span></div>
  <div class="panel-body" >
    <div class="col-lg-6">
      <%= form_for Group.new do |f| %>
        <h4><%= f.label :group, 'Name' %></h4>
        <div class="input-group input-group-lg">
          <%= f.text_field :name, class: "form-control", placeholder: "Group name" %>
          <%= f.hidden_field :owner_id, value: current_user.id %>
          <span class="input-group-btn">
            <%= f.submit 'Create', class: "btn btn-primary"%>
          </span>
        </div>
      <% end %>
    </div>
    <div class="col-lg-6">
      <p class="help-block">Choose a name for your Group. You can start adding members after you click Create.</p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<%= content_for :page_title, "Group: #{@group.name}" %>
<%= content_for :body_id, 'groups' %>
<%= content_for :body_class, 'show' %>
<%= stylesheet_link_tag "groups" %>
<% if in_group(params[:id])%>
  <div class="panel panel-default">
    <div class="panel-heading">
      <span class="panel-title"> <%= @group.name %> </span>
    </div>
    <!-- / .panel-heading -->
    <div class="panel-body">
      <div class="col-md-9">
        <table class="table table-striped table-bordered">
          <tr>
            <th> Name </th>
            <th> Role </th>
          </tr>
          <% if !@memberships.empty? %>
            <% @memberships.includes(:user).each do |m| %>
              <tr>
                <% @user = m.user %>
                <td> <%= @user.firstname + " " + @user.lastname %></td>
                <td>
                  <% case m.role %>
                  <% when 'owner' %>
                    <% labelcolor = 'label-primary' %>
                  <% when 'manager' %>
                    <% labelcolor = 'label-warning' %>
                  <% else %>
                    <% labelcolor = 'label-default' %>
                  <% end %>
                  <span class="label <%= labelcolor %>"><%= m.role %> </span>
                </td>
              </tr>
            <% end #.each %>
          <% end #if%>
        </table>
      </div>
      <div class="col-md-3">
        <% if is_owner(params[:id]) or is_manager(params[:id]) %>
          <%= link_to edit_group_path(id: @group.id) , :class => 'btn btn-primary' do %>
            <i class="glyphicon glyphicon-pencil" title="Edit"></i> Manage
          <% end %>
        <% end %>
        <% unless is_owner(params[:id]) %>
          <%= link_to leave_path(:id => params[:id]), {:class=> 'btn btn-danger', data: {confirm: "Are you sure you want to leave this group?", toggle: 'tooltip', placement: 'top', original_title: 'Delete'}} do %>
            <i class="glyphicon glyphicon-remove" title="Edit"></i> Leave
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render "groups/permissions" %>

  <script type="text/javascript">
    function startGroupDetailTour() {

      var intro = introJs();
      intro.setOptions({
        doneLabel: 'OK',
        skipLabel: 'Exit tour',
        disableInteraction: true,
        showBullets: false,
        showStepNumbers: false,
        scrollToElement: false,
        exitOnOverlayClick: true,
        steps: [
          {
            element: '.panel',
            intro: "This is the detail page for the Group \"<%= @group.name %>\"."
          },
          {
            element: '.panel-body .col-md-9',
            intro: "The table on the left tells you each Group member's full name and role."
          },
          {
            element: '.panel-body .col-md-3',
            intro: "Owners and Managers will see a \"Manage\" button here to the right of the table, while Managers and Members will also see a button to \"Leave\" the Group."
          },
          <% if is_owner(params[:id]) or is_manager(params[:id]) %>
            {
              element: '.panel-body .col-md-3',
              intro: "Looks like you are an Owner or Manager of this group. Let's navigate to this Group's Management page."
            }
          <% else %>
            {
              element: '.panel-body .col-md-3',
              intro: "Looks like you are not an Owner or Manager of this group, so the tour will end here.<br /><br /> If you would like to learn about the Group Management page, please create a new Group (or ask a Group Owner to make you a Manager), then restart this tour from the dashboard."
            }
          <% end %>
        ]
      });
      intro.start().oncomplete(function() {
        <% if is_owner(params[:id]) or is_manager(params[:id]) %>
          window.location.href = "<%= edit_group_path(id: params[:id], tour: 'true') %>";
        <% end %>
      });
    }
    if("<%= params[:tour] %>" == "true"){
      startGroupDetailTour();
    }
  </script>
<% else %>
  You do not have permission to view this page.
<% end %>