config/routes.rb
AnnotationStudio::Application.routes.draw do
  use_doorkeeper

  get "public/:id" => "public_documents#show"
  get "review/:id" => "public_documents#show"

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks",
                                    sessions: "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :documents do
    resources :annotations
    post :set_default_state
    post :publish
    post :publicize
    post :archive
    post :snapshot
    get :export
  end

  resources :users, only: [:show, :edit]

  authenticated :user do
    root :to => "users#show"
    get "dashboard", to: "users#show", as: :dashboard

    post "annotations", to: "annotations#search"
    get "annotations", to: "annotations#index"
    get "annotations/:id", to: "annotations#show"
    get "documents/:document_id/annotations/field/:field", to: "annotations#field"
    get "leave" => "groups#leave"

    #post 'join_via_name' => "groups#join_via_name" #for joining new groups via name entry

    resources :groups

    #should they be post instead?
    get "remove_member", to: "groups#remove_member"
    post "update_member_role", to: "groups#update_member_role"

    resources :invites

    get "toggleIS", to: "groups#toggleIS"
    post "toggleIS", to: "groups#toggleIS"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"

      #invite link for unauthenticated user
      get "/dashboard" => "devise/sessions#new"
    end
  end

  get "exception_test" => "annotations#exception_test"
  # root :to => "devise/sessions#new"

  namespace :api do
    namespace :v1 do
      # api routes
      get "/me" => "credentials#me"
      get "/my_groups" => "credentials#my_groups"
      get "/group_members" => "credentials#group_members"
      post "/docmeta" => "docmeta#docmeta"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable, :rememberable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable, :validatable, :confirmable,
         :timeoutable, :omniauthable, :omniauth_providers => [:wordpress_hosted]

  validates :agreement, presence: { message: "must be checked. Please check the box to confirm you have read and accepted the terms and conditions." }

  extend FriendlyId
  friendly_id :username, use: [:slugged, :history]

  acts_as_role_user

  has_many :documents

  has_many :memberships, :foreign_key => "user_id"
  has_many :groups, through: :memberships
  accepts_nested_attributes_for :memberships


  # Doesn't handle missing values.
  def fullname
    "#{firstname} #{lastname}"
  end

  def username
    "#{firstname.downcase}#{lastname.first.downcase}"
  end

  # Doesn't handle missing values.
  def first_name_last_initial
     "#{firstname} #{lastname.first}."
  end

  # Doesn't handle missing values.
  def first_initial_last_name
     "#{firstname.first}. #{lastname}"
  end

  def has_document_permissions?(document)
    self.has_role?(:admin) || self == document.user
  end

  def self.all_tags()
    tags = User.groups.map{|t| t.name}
    return tags.sort!
  end

  def admin?
    roles.pluck(:name).include? 'admin'
  end

  def self.find_for_wordpress_oauth2(auth, current)
    authed_user = User.where(email: auth.info.email.downcase).first_or_initialize do |user|
      user.firstname = auth.info.name.split(' ').first
      user.lastname = auth.info.name.split(' ').length > 1 ? auth.info.name.split(' ').last : " "
      user.agreement = true
      user.password = Devise.friendly_token[0,20]
    end
    authed_user.provider = auth.provider
    authed_user.uid = auth.uid
    if authed_user.new_record?
      authed_user.skip_confirmation!
    end
    if authed_user.save
      authed_user
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    if params[:id].nil? # if there is no user id in params, show current one
      @user = current_user
    else
      @user = User.where(:id => params[:id])
    end
    @document_list = Document.select(:slug, :title) # for getting document name in annotations table.

    whitelisted = params.permit(:docs, :page, :group)

    per_page = 10
    docs = helpers.getSharedDocs() #see application_helper.rb

  #AUTOCOMPLETE

    #for document search autocomplete (user's docs and shared group docs)
    shared_t = docs.pluck(:title)
    my_t = current_user.documents.pluck(:title)

    @titleSuggestions = shared_t | my_t
    @authorSuggestions = docs.pluck(:author) | current_user.documents.pluck(:author)
    @groupSuggestions = current_user.groups.pluck(:name)

  #END AUTOCOMPLETE
    @sharedDocsCount = docs.size

  #ajax 

    #GROUP SORT AJAX 
    @groupMode = params[:gPage]

    owned = current_user.groups.where(owner_id: current_user.id).paginate(:page => whitelisted[:page], :per_page => per_page)
    joined = current_user.groups.paginate(:page => whitelisted[:page], :per_page => per_page)

    filter = params[:filter]
    if filter == "timeASC"
      @joinedGroups = joined.order('created_at ASC')
      @mygroups = owned.order('created_at ASC') 
    else
      @joinedGroups = joined.order('created_at DESC')
      @mygroups = owned.order('created_at DESC') 
    end

    #DOCUMENT SORT AJAX
    @docMode = params[:dPage]
    shared = docs.paginate(:page => whitelisted[:page], :per_page => per_page)
    mine = current_user.documents.paginate(:page => whitelisted[:page], :per_page => per_page)

    case params[:dFilter]
      when "timeASC"
        @sharedDocs = shared.order('created_at ASC')
        @myDocs = mine.order('created_at ASC')

      when "A-Z"
        @sharedDocs = shared.order('title ASC')
        @myDocs = mine.order('title ASC')

      when "Z-A"
        @sharedDocs = shared.order('title DESC')
        @myDocs = mine.order('title DESC')

      else #"timeDESC" is default
        @sharedDocs = shared.order('created_at DESC')
        @myDocs = mine.order('created_at DESC')

    end #case

    #toggle ajax option for show.js.erb
    @ajaxOption = params[:dFilter] ? "document" : "group"

  #END AJAX 

    #handling invite_token. need to put here because invite_token is a param of dashboard route
    @invitetoken = params[:invite_token]
    if @invitetoken 

      #make sure token is valid 
      begin
        invite = Invite.find_by(token: @invitetoken)
        
        #check for expiration 
        unless invite.expiration_date && (invite.expiration_date < Time.now)
          org =  invite.group #find the user group attached to the invite
          current_user.groups << org #add this user to the new user group as a member
          flash[:alert] = 'Successfully joined group!'

        else
          flash[:error] = 'Token expired. please get new token'
          redirect_to dashboard_path
          return

        end #end unless

      rescue ActiveRecord::RecordNotUnique
        flash[:error] = 'Already in group'

      rescue NoMethodError #if token is invalid, org will call .group on a nil class which returns this error
        flash[:error] = 'Invalid token'
        
      end #end begin-rescue
      redirect_to dashboard_path
    end #end if 
   
    respond_to do |format|
      format.html # show.html.erb
      format.json {render json: @user}
      format.js #ajax
    end

    gon.rabl template: 'app/views/users/show.rabl', as: 'user'
  end

  def edit
    @user = User.where(:id => params[:id])
  end

  def users_params
    params.require(:user).permit(:email, :password, :agreement, :affiliation, :password_confirmation,
                                 :remember_me, :firstname, :lastname, :first_name_last_initial, 
                                 :username, :nav, :filter, :groups)
  end
end

app/views/users/_joined_groups.html.erb
 <div class="row">
  <% @joinedGroups.each do |g| %>
    <div class= "column">
      <div class="title"> <%= link_to g.name, group_path(id: g.id) %> <br> </div>

      <div class="h_line"></div>


       <% myRole = Membership.find_by(group_id: g.id, user_id: current_user.id).role %>
       Role: <%= myRole %> <br>

       Owner: <%= User.find(g.owner_id).firstname %><br>
       
       <% m = Membership.where(group_id: g.id) %>
       Members: <%= m.size %> 

    </div>
  <% end %>

  </div>

<center>
  <div class='pagination-controls'>
      <%= will_paginate @joinedGroups, renderer: BootstrapPagination::Rails %>
    </div>
</center>
  

app/views/users/_leftnav.html.erb
<!-- users/_leftnav.html.erb -->

app/views/users/_my_groups.html.erb
<div class="row">

  <% @mygroups.includes(:memberships).each do |g| %>
    <div class= "column">
       <div class="title"> <%= link_to g.name, group_path(id: g.id) %> <br> </div>


        <div class="tile-content">
       <div class="h_line"></div>
        Owner: <%=current_user.firstname=%><!--%= User.find(g.owner_id)%--><br>
        Members: <%= g.memberships.size %> <br>
        Editors: <%= g.memberships.where(role: "manager").size %>

           </div> <!-- tile-content-->

       <br>
       <br>

       <button class="editButton" ><%= link_to "Manage", edit_group_path(id: g.id) %></button>

    </div>
  <% end %>
  </div>

<center>
  <div class='pagination-controls'>
      <%= will_paginate @mygroups, renderer: BootstrapPagination::Rails %>
    </div>
</center></center></center></center></center>

app/views/users/_rightnav.html.erb
<!-- users/_rightnav.html.erb -->
<ul class="nav navmenu-nav" id="usernav">
  <!-- documents/_leftnav.html.erb -->
  <% if user_signed_in? %>
  <li class="<%= 'active' if current_page?(dashboard_path) || current_page?(root_path) %>"><%= link_to("Dashboard", "/dashboard", :id => "dashboard-link") %></li>
  <li class="<%= 'active' if current_page?(documents_path) %>"><%= link_to("Documents", "/documents", :id => "documents-link") %></li>
  <li class="<%= 'active' if current_page?(annotations_path) %>"><%= link_to("Annotations", "/annotations", :id => "annotations-link") %></li>
  <li class="<%= 'active' if current_page?(groups_path) %>"><%= link_to("Groups", "/groups", :id => "groups-link") %></li>
  <li class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to("My Profile", edit_user_registration_path, :id => "user-account-edit") %></li>
  <li class="<%= 'active' if current_page?(destroy_user_session_path) %>"><%= link_to('Logout', destroy_user_session_path) %></li>
  <% if can? :manage, UserSet %>
  <li class="<%= 'active' if current_page?(admin_users_path) %>"><%= link_to(raw('Manage Users <i class="fa fa-external-link-square"></i>'), admin_users_path, :target => '_blank') %></li>
  <% end %>
  <% else %>
  <li class="<%= 'active' unless current_page?(new_user_registration_path) %>"><%= link_to('Login', new_user_session_path)  %></li>
  <li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to('Register', new_user_registration_path)  %></li>
  <% end %>
  <li><a href="http://support.annotationstudio.org/" target="_blank">Help <i class="fa fa-external-link-square"></i></a></li>
</ul>

app/views/users/_side_search_options.html.erb
<div style="padding-left:50px; padding-top:35px; z-index: 1;" >


<!--Group search and sort-->
<% if params[:nav] && (params[:nav].include? "groups") %>

<h4> Groups Search </h4>

<%= form_tag groups_path, :method => 'get' do %>
	<p class="greyText">Search by Group name</p>
	<%= text_field_tag 'search', nil, id: 'dash-groups-search', class: "searchTextField" %>
	<%= submit_tag "Search" , class: "submit"%>
<% end #form_tag %>
<br>

<h4> Sort </h4>
    <%= form_tag groups_path, :method => 'get', :data => {remote: true} do %>
        <table >
            <tr>
                <td class="radioButton"> <%= radio_button_tag 'time', 'timeASC', nil, onchange: "groupSort(this)"%> 
                 <%= label_tag :title, 'Time Ascending (oldest first)' %> </td>
            </tr>
            <tr>
                <td class="radioButton"><%= radio_button_tag 'time', 'timeDESC', true, onchange: "groupSort(this)" %>
                <%= label_tag :title, 'Time Descending (newest first)' %> </td>

            </tr>
        </table>
    <% end %>

<!--annotation search-->
<% elsif params[:nav] && (params[:nav].include? "annotations") %>

	<h4> Annotations Search </h4>
	<p class="greyText" > Search by: </p>

	<%= form_tag :controller=> 'annotations', :action=> 'search' do %>
		<table>
			<tr> 
				<td class="radioButton"><%= radio_button_tag 'method', "user", true %> 
				 Annotator's first name </td>
			</tr>
			<tr>
				<td class="radioButton"><%= radio_button_tag 'method', 'groups' %> 
				Groups (only shared annotations)</td>
			</tr>
		</table>
		<br>
		
		<%= text_field_tag 'search', nil, id: 'dash-annotations-search', class: "searchTextField" %>
		<%= submit_tag "Search", class: "submit" %>
<% end #form_tag %>



<!--document search-->
<% else %>

<h4> Documents Search </h4>

<%= form_tag documents_path, :method => 'get' do %>
	<p class="greyText"> Search by: </p>



	<table >
		<tr > 
			<td class="radioButton"><%= radio_button_tag 'method', 'title', true, onchange: "opt(this)"%> <%= label_tag :title, 'Title' %></td>
		</tr>
		<tr >
			<td class="radioButton"><%= radio_button_tag 'method', 'author', nil, onchange: "opt(this)" %> <%= label_tag :title, 'Author' %></td>
		</tr>
		<tr >
			<td class="radioButton"> <%= radio_button_tag 'method', 'status', nil, onchange: "opt(this)" %> <%= label_tag :title, 'Status' %></td>
		</tr>
		<tr> 
			<td class="radioButton"> <%= radio_button_tag 'method', 'group', nil, onchange: "opt(this)" %> <%= label_tag :title, 'Group' %> </td>
		</tr>
	</table></br>


	<%= text_field_tag 'search', nil, id: 'dash-documents-search', class: "searchTextField" %>
	<%= submit_tag "Search", class: "submit" %>

	<h4> Sort </h4>
		<%= form_tag documents_path, :method => 'get', :data => {remote: true} do %>

			<table class="search-options">
				<tr>
					<td class="radioButton"><%= radio_button_tag 'filter', 'timeDESC', true, onchange: "docSort(this)" %> <%= label_tag :title, 'Newest first' %> </td>
				</tr>

				<tr>
					<td class="radioButton"> <%= radio_button_tag 'filter', 'timeASC', nil, onchange: "docSort(this)" %> <%= label_tag :title, 'Oldest first' %> </td>
				</tr>
				<tr>
					<td class="radioButton"> <%= radio_button_tag 'filter', 'A-Z', nil, onchange: "docSort(this)" %> <%= label_tag :title, 'A-Z' %> </td>
				</tr>
				<tr>
					<td class="radioButton"> <%= radio_button_tag 'filter', 'Z-A', nil, onchange: "docSort(this)" %> <%= label_tag :title, 'Z-A' %> </td>
				</tr>

			</table>

		<% end #sort form_tag%>
	<% end #form_tag %>

<% end %>

</div>

<script>

	//default autocomplete for docs
	$("#dash-documents-search").autocomplete({
		source: <%= raw(@titleSuggestions) %>
	});

	//onchange function for doc search method
	function opt(obj){
		var selected = obj.value;
		var data;
		switch(selected){
			default: 
				data = <%= raw(@titleSuggestions) %>;
				break;
			case 'author':
				data = <%= raw(@authorSuggestions) %>;
				break;
			case 'status':
				data = ["published", "draft", "archived"];
				break;
			case 'group':
				data = <%= raw(@groupSuggestions) %>;
		} //end switch

		$("#dash-documents-search").autocomplete({
			source: data
		}); //end autocomplete
		
	} //end opt

	//group sort/filter ajax
	function groupSort(obj){
		var selected = obj.value;
		var location = "<%= params[:nav]%>"
		$.ajax({
		    url: "/dashboard",
		    type: "GET",
		    data: {filter: selected, gPage: location},
		    dataType: 'script'
		}); //end ajax
	}

	//group autocomplete
	$("#dash-groups-search").autocomplete({
		source: <%= raw(@groupSuggestions) %>
	});


	//doc sort/filter ajax
	function docSort(obj){
		var selected= obj.value;
		var location = "<%= params[:nav]%>"
		$.ajax({
			url: "/dashboard",
		    type: "GET",
		    data: {dFilter: selected, dPage: location},
		    dataType: 'script'
		});
	}

	

</script>

app/views/users/show.html.erb
<%= content_for :body_id, 'dashboard' %>
<%= content_for :body_class, 'index' %>
<%= content_for :page_title, 'Dashboard' %>
<%= stylesheet_link_tag "users" %>
<%= render "/shared/document_titles" %>
                             
<% if ENV["GLOBAL_ALERT"] != "" %>
  <div class="row">
    <div class="col-md-12" id="blurb">
        <div class="alert alert-dismissible alert-<%= ENV["ALERT_LEVEL"] %>" role="alert">
          <%= ENV["GLOBAL_ALERT"].html_safe %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </div>
    </div>
  </div>
<% end %>

<div id="users" class="row">
  <div class="col-md-6">
    <div class="panel panel-default" id="dashboard-documents">
      <div class="panel-heading">
        <span class="panel-title"><%= link_to "Documents", documents_path %></span>
        <ul class="nav nav-tabs nav-tabs-xs pull-right" id="document-tabs" role="tablist">
          <li class="active"><a href="#assigned" data-toggle="tab"><span class="badge"><%= @sharedDocs.size %></span> Shared</a></li>
          <li><a href="#created" data-toggle="tab"><span class="badge"><%= current_user.documents.size %></span> Mine</a></li>
        </ul>
      </div>
      <!-- / .panel-heading -->
      <div class="tab-content">
        <div class="tab-pane no-padding fade active in" id="assigned">
          <ul id="documents-assigned" class="list-group">
            <% unless @sharedDocs.empty? || @sharedDocs.nil? %>
              <% @sharedDocs.order("created_at DESC").where.not(state: 'draft').limit(10).each do |document| %>
                <li class="list-group-item">
                  <%= link_to document.title.truncate(40), document_path(document.friendly_id) %>
                  <span class="pull-right">
                    <% if !document.groups.empty? %>
                      <% document.groups.take(2).each do |g| %>
                        <a class="label label-info" href="<%= group_path(id: g.id) %>"><%= g.name.truncate(16) %></a>&nbsp;
                      <% end %>
                      <% if document.groups.length > 2 %>
                        <a class="label label-default" href="<%= documents_path(docs: 'assigned') %>">+<%= (document.groups.length-2).to_s %></a>&nbsp;
                      <% end %>
                    <% end %>
                    <%= document.created_at.strftime("%m/%d/%Y") %></span>
                </li>
              <% end %>
              <li class="list-group-item"><strong><a href="<%= documents_path(docs: 'assigned') %>">See all shared documents&hellip;</a></strong></li>
            <% else %>
              <li class="list-group-item">
                No documents to view.
              </li>
            <% end %></ul>
          <ul class="nav nav-pills">
            <li><%= link_to raw("<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span> Create new document"), document_path('new') %></li>
          </ul>
        </div>
        <!-- / .tab-pane -->
        <div class="tab-pane no-padding fade in" id="created">
          <ul id="documents-created" class="list-group">
            <% unless current_user.documents.empty? || current_user.documents.nil? %>
              <% current_user.documents.order("created_at DESC").limit(10).each do |document| %>
                <% if can? :read, document %>
                  <li class="list-group-item">
                    <%= link_to document.title.truncate(40), document_path(document.friendly_id) %>
                    <span class="pull-right">
                      <% if !document.groups.empty? %>
                        <% document.groups.take(2).each do |g| %>
                          <a class="label label-info" href="<%= group_path(id: g.id) %>"><%= g.name.truncate(16) %></a>&nbsp;
                        <% end %>
                        <% if document.groups.length > 2 %>
                          <a class="label label-default" href="<%= documents_path(docs: 'created') %>">+<%= (document.groups.length-2).to_s %></a>&nbsp;
                        <% end %>
                      <% end %>
                      <%= document.created_at.strftime("%m/%d/%Y") %></span>
                  </li>
                <% end %>
              <% end %>
              <li class="list-group-item"><strong><a href="/documents?docs=created">See all of my documents&hellip;</a></strong></li>
            <% else %>
              <li class="list-group-item">
                No documents to view.
              </li>
            <% end %>
          </ul>
          <ul class="nav nav-pills">
            <li><%= link_to raw("<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span> Create new document"), document_path('new') %></li>
          </ul>
        </div>
      </div>
      <!-- / .tab-pane -->
    </div>
    <!--/ panel -->
    <div class="panel panel-default" id="dashboard-groups">
      <div class="panel-heading">
        <span class="panel-title">
          <%= link_to 'Groups', groups_path %></span>
        <a class="btn btn-default btn-sm" id="groups-tour"><i class="fa fa-info-circle"></i> &nbsp;How to use Groups</a>
      </div>
      <!-- / .panel-heading -->
      <div class="tab-content">
        <div class="tab-pane no-padding fade active in" id="groups">
          <ul class="list-group">
            <% if !current_user.groups.empty? %>
              <% current_user.groups.each do |group| %>
                <li class="list-group-item"><%= link_to group.name.truncate(50), group_path(id: group.id) %>
                  <span class="pull-right">
                    <% myRole = Membership.find_by(group_id: group.id, user_id: current_user.id).role %>
                    <% case myRole %>
                    <% when 'owner' %>
                      <% labelcolor = 'label-primary' %>
                    <% when 'manager' %>
                      <% labelcolor = 'label-warning' %>
                    <% else %>
                      <% labelcolor = 'label-default' %>
                    <% end %>
                    <span class="label <%= labelcolor %>"><%= myRole %> </span>
                  </span>
                </li>
              <% end %>
               <li class="list-group-item"><strong><a href="/groups">See all groups&hellip;</a></strong></li>
            <% else %>
              <li class="list-group-item">
                You are not a member or owner of any Groups.
              </li>
            <% end %>
          </ul>
          <ul class="nav nav-pills">
            <li><%= link_to raw("<span class=\"glyphicon glyphicon-plus\" aria-hidden=\"true\"></span> Create new group"), group_path('new') %></li>
          </ul>
        </div>
      </div>
    </div>
    <!--/ panel -->
  </div>
  <!--/ col-md-6 -->
  
  <div class="col-md-6">
    <div class="panel panel-default" id="dashboard-annotations">
      <div class="panel-heading">
        <span class="panel-title">
          <%= link_to "Annotations", annotations_path %></span>
        <ul class="nav nav-tabs nav-tabs-xs pull-right" id="annotation-tabs" role="tablist">
          <li>
            <a href="#class" data-toggle="tab">
              <span class="badge"><i class="fa fa-spinner fa-spin"></i></span>
              Shared
            </a>
          </li>
          <li class="active">
            <a href="#mine" data-toggle="tab">
              <span class="badge"><i class="fa fa-spinner fa-spin"></i></span>
              Mine
            </a>
          </li>
        </ul>
      </div>
      <!-- / .panel-heading -->
      <div class="tab-content">
        <div class="tab-pane no-padding fade in" id="class">
          <ul id="class-annotation-list" class="list-group"><div class="panel-body loading"><i class="fa fa-spinner fa-spin"></i></div></ul>
        </div>
        <div class="tab-pane no-padding fade in active" id="mine">
          <ul id="my-annotation-list" class="list-group"><div class="panel-body loading"><i class="fa fa-spinner fa-spin"></i></div></ul>
        </div>
      </div>
      <!--<ul class="nav nav-pills">-->
      <!--<li>-->
      <!--  <%#= link_to "Go to annotation list", annotations_path %></li>-->
      <!--</ul>-->
    </div>
    <!--/ panel --> </div>
  <!--/col-md-3 -->
</div>
<!--/row -->
<%= javascript_include_tag "widget" %>
<script type="text/javascript" charset="utf-8">
  jQuery(function ($) {
    var widget = new Widget.App();
    var endpoint = location.protocol+'//'+'<%= ENV["API_URL"] %>';
    var token = '<%= session["jwt"] %>';
    var group_ids = [];
  <% current_user.groups.each do |g| %>
    group_ids.push(<%=g.id %>);
  <% end %>
    var myLoadOptions = {
      'limit': 10,
      'group_ids': group_ids,
      'host': location.host,
      'user': "<%= current_user.email %>",
      'mode': 'user',
      'context': 'dashboard',
    };
    var classLoadOptions = {
      'limit': 10,
      'group_ids': group_ids,
      'host': location.host,
      'user': "<%= current_user.email %>",
      'mode': 'groupId',
      'context': 'dashboard',
    };
    widget.listAnnotations('my-annotation-list', myLoadOptions, endpoint, token);
    widget.listAnnotations('class-annotation-list', classLoadOptions, endpoint, token);
  });

  // Groups intro tour
  function startGroupsTour(){
    var intro = introJs();
    intro.setOptions({
      doneLabel: 'OK',
      skipLabel: 'Exit tour',
      disableInteraction: true,
      showBullets: false,
      showStepNumbers: false,
      scrollToElement: false,
      exitOnOverlayClick: true,
      steps: [
        {
          element: '#dashboard-groups',
          intro: "Welcome to the Groups system in Annotation Studio. Groups are now the main way to share documents and annotations with other users. \<br \/\>\<br \/\> If you get lost during this tour, you can restart it by returning to this page and clicking the button again."
        },
        {
          element: '#dashboard-groups',
          intro: "Groups can be viewed at a glance on the dashboard here."
        },
        <% if current_user.groups.empty? %>
          {
            element: '#dashboard-groups .tab-content .tab-pane ul li:first-child',
            intro: "Looks like you are not a member or owner of any Groups."
          }, 
          {
            element: '#dashboard-groups .tab-content .tab-pane .nav-pills li:first-child',
            intro: "Click here to create a new Group."
          }
        <% else %>
          {
            element: '#dashboard-groups .tab-content .tab-pane ul li:first-child',
            intro: "Here is one of your Groups."
          },
          {
            element: '#dashboard-groups .tab-content .tab-pane ul li:first-child .label',
            intro: "This label indicates your role in the Group: member, manager, or owner."
          },
          {
            element: '#dashboard-groups .tab-content .tab-pane .nav-pills li:first-child',
            intro: "You can quickly navigate to the Group creation page here."
          },
          {
            element: '#dashboard-groups .tab-content .tab-pane ul li:last-child',
            intro: "Let's navigate to the Groups overview page."
          }
        <% end %>
        ]
      });
    intro.start().oncomplete(function() {
    <% if !current_user.groups.empty? %>
      window.location.href = "<%= groups_path(tour: 'true') %>";
    <% end %>
    });
  }
  $(document).ready(function(){
  $('#groups-tour').click(startGroupsTour);
  });
</script>
<script type="text/template" id="user-comment-template">
  <span class="user-highlight"><span class="pull-right">{{formattedDate}}</span><div class="ellipsis"><a href="{{uri}}?mine={{mine}}#hl{{uuid}}">{{{quote}}}</a></div></span>
  <span class="user-comment"><div class="ellipsis">{{{text}}}</div><div class="secondary-text">{{title}} ({{username}})</div></span>
</script>
<script type="text/template" id="user-highlight-template">
  <span class="user-highlight"><span class="pull-right">{{formattedDate}}</span><div class="ellipsis"><a href="{{uri}}?mine={{mine}}#hl{{uuid}}">{{{quote}}}</a></div></span>
  <span class="user-comment"><div class="secondary-text">{{title}} ({{username}})</div></span>
</script>