config/routes.rb
AnnotationStudio::Application.routes.draw do
  use_doorkeeper

  get "public/:id" => "public_documents#show"
  get "review/:id" => "public_documents#show"

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks",
                                    sessions: "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :documents do
    resources :annotations
    post :set_default_state
    post :publish
    post :publicize
    post :archive
    post :snapshot
    get :export
  end

  resources :users, only: [:show, :edit]

  authenticated :user do
    root :to => "users#show"
    get "dashboard", to: "users#show", as: :dashboard

    post "annotations", to: "annotations#search"
    get "annotations", to: "annotations#index"
    get "annotations/:id", to: "annotations#show"
    get "documents/:document_id/annotations/field/:field", to: "annotations#field"
    get "leave" => "groups#leave"

    #post 'join_via_name' => "groups#join_via_name" #for joining new groups via name entry

    resources :groups

    #should they be post instead?
    get "remove_member", to: "groups#remove_member"
    post "update_member_role", to: "groups#update_member_role"

    resources :invites

    get "toggleIS", to: "groups#toggleIS"
    post "toggleIS", to: "groups#toggleIS"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"

      #invite link for unauthenticated user
      get "/dashboard" => "devise/sessions#new"
    end
  end

  get "exception_test" => "annotations#exception_test"
  # root :to => "devise/sessions#new"

  namespace :api do
    namespace :v1 do
      # api routes
      get "/me" => "credentials#me"
      get "/my_groups" => "credentials#my_groups"
      get "/group_members" => "credentials#group_members"
      post "/docmeta" => "docmeta#docmeta"
    end
  end
end

app/views/shared/_annotation-header.html.erb
<ol class="breadcrumb breadcrumb-inverse hidden-xs">
<% if params[:controller] == 'documents' %>
  <% if params[:action] == 'show' %>
    <li>Annotations</li>
  <% end %>
<% end %>
</ol>

app/views/shared/_annotation_header.html.erb
<ol class="breadcrumb breadcrumb-inverse hidden-xs">
<% if params[:controller] == 'documents' %>
  <% if params[:action] == 'show' && !@document.nil? && ! @document.draft?  %>
    <li class="annotations-header">Annotations</li>
  <% end %>
<% end %>
</ol>

app/views/shared/_annotator_base.html.erb
<div id="annotation-well" class="affix">

  <ul id="annotation-list" style="padding-left: 8px;">

    <form class="btn-group btn-group-sm" data-toggle="buttons" id="view-chooser" style="padding-top: 8px;">
      <label class="btn btn-default btn-sm viewchoice 
        <% if !params[:mine] || params[:mine] == 'true' %>
          active
        <% end %>
        " id="user">
        <input name="viewchoice" type="radio" 
        <% if !params[:mine] || params[:mine] == 'true' %>
          checked 
        <% end %>
        value="user">Mine</input>
      </label>

      <label class="btn btn-default btn-sm viewchoice
        <% if params[:mine] == 'false' %>
          active
        <% end %>" id="groupId">
        <input name="viewchoice" type="radio" 
        <% if params[:mine] == 'false' %>
          checked 
        <% end %>
        value="groupId">Groups</input>    
      </label>
      <% if current_user.has_role?(:admin) %>
      <label class="btn btn-default btn-sm viewchoice" id="admin">
        <input name="viewchoice" type="radio" value="admin">All</input>
      </label>
      <% end %>
    </form>

    <div class="btn-group btn-group-sm" data-toggle="buttons" id="filter-chooser" style="padding-top: 8px;">
      <label class="btn btn-default btn-sm active" id="allannotations">
        <input type="radio" class="btn btn-default btn-sm active" checked value="allannotations">Whole text</input>
      </label>
      <label class="btn btn-default btn-sm" id="visibleannotations">
        <input type="radio" class="btn btn-default btn-sm" value="visibleannotations">Visible text</input>
      </label>
    </div>
  </ul>

  <script type="text/template" id="comment-template">

    <span class="handle"><span class="glyphicon glyphicon-option-vertical"></span></span>
    <span id="sb{{uuid}}" href="#full{{uuid}}" data-highlight="#hl{{uuid}}" rel="tooltip" title="{{username}}" class="highlightlink comment">{{{text}}}</span>
    <span id="quote{{uuid}}" class="sbquote details">&quot;{{{quote}}}&quot;</span>
    <span id="text{{uuid}}" class="sbtext details">{{{text}}}</span>
    <span id="info{{uuid}}" class="sbinfo details">{{username}}</span>
    <div id="tags{{uuid}}" class="sbtags details">{{#tags}}<span class="label label-default">{{.}}</span> {{/tags}}</div>
  </script>


  <script type="text/template" id="highlight-template">

    <span class="handle"><span class="glyphicon glyphicon-option-vertical"></span></span>
    <span id="sb{{uuid}}" data-highlight="#hl{{uuid}}" rel="tooltip" title="{{username}}" class="highlightlink highlight sbquote">&quot;{{{quote}}}&quot;</span>
    <span id="quote{{uuid}}" class="sbquote details">&quot;{{{quote}}}&quot;</span>
    <div id="tags{{uuid}}" class="sbtags details">{{#tags}}<span class="label label-default">{{.}}</span> {{/tags}}</div>
  </script>
</div><!--/well -->

app/views/shared/_backbone_libraries.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/backbone.js/1.2.3/backbone-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.2.0/mustache.min.js"></script>

app/views/shared/_breadcrumbs.html.erb
<% second_line = params[:controller] == 'documents' && (params[:action] == 'show' || params[:action] == 'edit') %>
<ol class="breadcrumb breadcrumb-inverse hidden-xs<%= " second-line" if second_line %>">
  <% if current_page?(dashboard_path) || current_page?(root_path) %>
    <li class="active">Dashboard</li>
  <% elsif !current_page?(page_path('cookiepolicy')) && !current_page?(page_path('terms')) && !current_page?(page_path('privacypolicy')) %>
    <li><%= link_to("Dashboard", "/dashboard", :id => "dashboard-link") %></li>
  <% end %>

  <% if current_page?(documents_path) %>
    <li class="active">Documents</li>
  <% elsif params[:controller] == 'documents' && !@document.nil? %>
    <li><%= link_to("Documents", "/documents", :id => "documents-link") %></li>
    <% if params[:action] == 'show' %>
      <li class="active"><%= @document.title %></li>
    <% elsif params[:action] == 'preview' %>
      <li class="active">Snapshot Preview of <%= @document.title %></li>
    <% elsif params[:action] == 'new' %>
      <li class="active">New Document</li>
    <% elsif params[:action] == 'edit' %>
      <li class="active">Editing: <%= @document.title %></li>
    <% end %>
  <% end %>

  <% if current_page?(annotations_path) %>
    <li class="active">Annotations</li>
  <% end %>

  <% if current_page?(groups_path) %>
    <li class="active">Groups</li>
  <% elsif params[:controller] == 'groups' && !@group.nil? %>
    <li><%= link_to("Groups", "/groups", :id => "documents-link") %></li>
    <% if params[:action] == 'show' %>
      <li class="active"><%= @group.name %></li>
    <% elsif params[:action] == 'new' %>
      <li class="active">New Group</li>
    <% elsif params[:action] == 'edit' %>
      <li class="active">Manage Group: <%= @group.name %></li>
    <% end %>
  <% end %>

  <% if current_page?(edit_user_registration_path) %>
    <li class="active">My Profile</li>
  <% end %>

  <% if current_page?(page_path('terms')) %>
    <li class="active">Terms and Conditions</li>
    <li>See also our our <%= link_to("Privacy Policy", page_path('privacypolicy')) %> and <%= link_to("Cookie Policy", page_path('cookiepolicy')) %>.</li>
  <% elsif current_page?(page_path('privacypolicy')) %>
    <li class="active">Privacy Policy</li>
    <li>See also our our <%= link_to("Cookie Policy", page_path('cookiepolicy')) %> and <%= link_to("Terms of Service", page_path('terms')) %>.</li>
  <% elsif current_page?(page_path('cookiepolicy')) %>
    <li class="active">Cookie Policy</li>
    <li>See also our our <%= link_to("Privacy Policy", page_path('privacypolicy')) %> and <%= link_to("Terms of Service", page_path('terms')) %>.</li>
  <% end %>

</ol>

app/views/shared/_default_brand.html.erb
<a class="navbar-brand" href="/">Annotation Studio <span style="color:<%= $DOMAIN_CONFIG['site_color'] %>;"><%= $DOMAIN_CONFIG['site_name'] %></span></a>

<ul class="nav navbar-nav pull-right hidden-xs" id="globalnav" >

  	<!--About-->
  <li><div class="dropdown">
	  <button class="dropdown-toggle menu-button" type="button" id="about-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		  About <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu" aria-labelledby="about-menu">
		  <li><a href="http://www.annotationstudio.org/project/" target="_blank">Project </a></li>
		  <li><a href="http://www.annotationstudio.org/pedagogy/" target="_blank">Pedagogy </a></li>
		  <li><a href="http://www.annotationstudio.org/community/" target="_blank">Community </a></li>
		  <li><a href="http://www.annotationstudio.org/support/" target="_blank">Support </a></li>
		  <li><a href="http://www.annotationstudio.org/news/" target="_blank">News </a></li>
	  </ul>
  </div></li>
  <!--About ends-->

<!--signed in-->
<% if user_signed_in? %>


	<li><a href="http://support.annotationstudio.org/" target="_blank">Help <i class="fa fa-external-link-square"></i></a></li>

	<li><div class="dropdown">
		<button class="dropdown-toggle menu-button" type="button" id="about-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<i class="fa fa-user" ></i> <%= current_user.fullname %> <span class="caret"></span>
			</button>
			<ul class="dropdown-menu" aria-labelledby="about-menu">
			<li class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to("My Profile", edit_user_registration_path, :id => "user-account-edit") %></li>
			<li class="<%= 'active' if current_page?(destroy_user_session_path) %>"><%= link_to('Logout', destroy_user_session_path) %></li>
		</ul>
		</div></li>

	<% if can? :manage, UserSet %>
		<li class="<%= 'active' if current_page?(admin_users_path) %>"><%= link_to(raw('Manage Users <i class="fa fa-external-link-square"></i>'), admin_users_path, :target => '_blank') %></li>
	<% end %>

<!--not signed in -->
<% else %>
	  <% if defined?(resource) != nil %>
	  <li><div class="dropdown dont-overflow">
		  <button class="dropdown-toggle menu-button" type="button" id="login-form" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
			  Log in
			  <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="login-form">
			  <li><%= render "/devise/sessions/sign_in" %></li>
		  </ul>
	  </div></li>

	  <li>
			<%= link_to "Register", new_registration_path(resource_name, :invite_token => params[:invite_token]) %></li>
	  <% end %>

<li><a href="http://support.annotationstudio.org/" target="_blank">Help <i class="fa fa-external-link-square"></i></a></li>
<% end %>
</ul>

app/views/shared/_default_footer.html.erb
    <div class="footer">
      <div class="container">
        <div class="pull-right footer-terms" style="text-align:right;">
          <span class="text-muted">&copy; <%= Time.now.year %> Active Archives Initiative at MIT</span><br />
          <span class="text-muted"><%= link_to("Terms and Conditions", page_path('terms')) %> | <%= link_to("Privacy Policy", page_path('privacypolicy')) %>  | <%= link_to("Cookie Policy", page_path('cookiepolicy')) %> </span></div>
        <p class="text-muted">
          <a href="http://web.mit.edu/" target="_blank"><img src="<%= asset_path("logo_mit.png") %>"></a><a href="https://aai.mit.edu/"><img src="<%= asset_path("aai-logo.png") %>" id="aai-logo"></a><a href="http://www.neh.gov/divisions/odh" target="_blank"><img src="<%= asset_path("neh_at_logo.png") %>" id="neh-logo"></a>
        </p>
      </div>
    </div>

app/views/shared/_document_titles.html.erb
<script type="text/javascript">
var documentList = {
<% @document_list.each { |document| %>
	'<%= document.slug %>': '<%= raw(document.title.gsub("'", "&apos;")) %>',
<% } %>
};
</script>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <%- next if type.to_s == 'timedout' %><%# per https://github.com/plataformatec/devise/issues/1777 %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissable fade in <%= self_removing(flash[:notice]) %>" id="mainalerts">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_noscript.html.erb
      <noscript>
          <div class="alert alert-danger">For Annotation Studio to work, it is necessary to enable JavaScript. Here are <a href="http://www.enable-javascript.com/" target="_blank"> instructions how to enable JavaScript in your web browser</a>.</div>
      </noscript>

app/views/shared/_user_menu.html.erb
  <ul class="nav navbar-nav pull-right hidden-xs" id="globalnav">
    <% if user_signed_in? %>
        <li class="<%= 'active' if current_page?(edit_user_registration_path) %>"><%= link_to("My Profile", edit_user_registration_path, :id => "user-account-edit") %></li>
        <li class="<%= 'active' if current_page?(destroy_user_session_path) %>"><%= link_to('Logout', destroy_user_session_path) %></li>
        <% if can? :manage, UserSet %>
        <li class="<%= 'active' if current_page?(admin_users_path) %>"><%= link_to(raw('Manage Users <i class="fa fa-external-link-square"></i>'), admin_users_path, :target => '_blank') %></li>
        <% end %>
    <% else %>
      <% if defined?(resource) != nil %>
      <li><div class="dropdown dont-overflow">
          <button class="dropdown-toggle menu-button" type="button" id="login-form" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Log in
              <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="login-form">
              <li><%= render "/devise/sessions/sign_in" %></li>
          </ul>
      </div></li>
      <li><div class="dropdown dont-overflow">
          <button class="dropdown-toggle menu-button" type="button" id="login-form" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Register
              <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="login-form">
              <li><%= render "/devise/sessions/sign_up" %></li>
          </ul>
      </div></li>
      <% end %>
    <% end %>
  </ul>