config/routes.rb
AnnotationStudio::Application.routes.draw do
  use_doorkeeper

  get "public/:id" => "public_documents#show"
  get "review/:id" => "public_documents#show"

  devise_for :users, controllers: { registrations: "registrations", omniauth_callbacks: "omniauth_callbacks",
                                    sessions: "sessions" }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :documents do
    resources :annotations
    post :set_default_state
    post :publish
    post :publicize
    post :archive
    post :snapshot
    get :export
  end

  resources :users, only: [:show, :edit]

  authenticated :user do
    root :to => "users#show"
    get "dashboard", to: "users#show", as: :dashboard

    post "annotations", to: "annotations#search"
    get "annotations", to: "annotations#index"
    get "annotations/:id", to: "annotations#show"
    get "documents/:document_id/annotations/field/:field", to: "annotations#field"
    get "leave" => "groups#leave"

    #post 'join_via_name' => "groups#join_via_name" #for joining new groups via name entry

    resources :groups

    #should they be post instead?
    get "remove_member", to: "groups#remove_member"
    post "update_member_role", to: "groups#update_member_role"

    resources :invites

    get "toggleIS", to: "groups#toggleIS"
    post "toggleIS", to: "groups#toggleIS"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"

      #invite link for unauthenticated user
      get "/dashboard" => "devise/sessions#new"
    end
  end

  get "exception_test" => "annotations#exception_test"
  # root :to => "devise/sessions#new"

  namespace :api do
    namespace :v1 do
      # api routes
      get "/me" => "credentials#me"
      get "/my_groups" => "credentials#my_groups"
      get "/group_members" => "credentials#group_members"
      post "/docmeta" => "docmeta#docmeta"
    end
  end
end

app/models/document.rb
# t.string   "title",               limit: 255
# t.text     "text"
# t.datetime "created_at",                      null: false
# t.datetime "updated_at",                      null: false
# t.string   "author",              limit: 255
# t.datetime "year_published"
# t.string   "edition",             limit: 255
# t.string   "publisher",           limit: 255
# t.string   "source",              limit: 255
# t.string   "rights_status",       limit: 255
# t.string   "slug",                limit: 255
# t.integer  "user_id"
# t.text     "publication_date"
# t.text     "chapters"
# t.string   "state",               limit: 255
# t.string   "upload_file_name",    limit: 255
# t.string   "upload_content_type", limit: 255
# t.integer  "upload_file_size"
# t.datetime "upload_updated_at"
# t.datetime "processed_at"
# t.string   "survey_link",         limit: 255
# t.text     "default_state"
# t.text     "snapshot"
# t.string   "cove_uri"

require "babosa" # allows cyrillic, other characters in titles (transliterates titles for URL use)

class Document < ApplicationRecord
  belongs_to :user, :autosave => true
  before_validation :add_title, on: :create, unless: :title?
  before_create :add_processed_at, unless: :uploaded?
  ALLOWED_CONTENT_TYPES = %w|application/msword
                             application/vnd.openxmlformats-officedocument.wordprocessingml.document
                             application/pdf
  |

  has_attached_file :upload
  validates_attachment_content_type :upload,
    content_type: ALLOWED_CONTENT_TYPES,
    message: "Filetype is not allowed. Please copy and paste the text instead, or choose another file."

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history, :finders]

  #new groups table structure:
  has_and_belongs_to_many :groups

  # #make title mandatory.
  # validates_presence_of :title --> not working?? document is still being created. problem possibly with
  #respond to do: format html

  scope :publicly, -> { where(:state => "public").order("id desc") }
  scope :active, -> { where("state != ?", "deleted").order("id desc") }

  STATES = %w{ pending draft published archived public }

  STATES.each do |state|
    define_method("#{state}?") do
      self.state == state
    end

    define_method("#{state}!") do
      self.update_attribute(:state, state)
    end
  end

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :russian).to_s
  end

  def processed?
    processed_at.present?
  end

  def members
    # binding.pry
    User.tagged_with(this.tag_list)
  end

  def uploaded?
    upload_file_name.present?
  end

  def add_processed_at
    self.processed_at = Time.now
  end

  def title?
    title.present?
  end

  def add_title
    self.title = "Untitled"
  end
end

app/controllers/documents_controller.rb
require "json"

class DocumentsController < ApplicationController
  before_action :find_document, :only => [:show, :set_default_state, :preview, :archive, :publicize, :publish, :export, :snapshot, :destroy, :edit, :update]
  before_action :authenticate_user!
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  load_and_authorize_resource :except => :create

  # GET /documents
  # GET /documents.json
  def index #search results
    whitelisted = params.permit(:docs, :page, :group)
    if !%w[ assigned created all ].include?(whitelisted[:docs])
      document_set = "assigned"
    else
      document_set = whitelisted[:docs]
    end

    @tab_state = { document_set => "active" }

    shared = helpers.getSharedDocs() #see application_helper.rb
    mine = current_user.documents

    per_page = 20

    myvisible = shared | mine

    if document_set == "assigned"
      @documents = shared.where.not(state: "draft").paginate(:page => whitelisted[:page], :per_page => per_page).order("created_at DESC")
    elsif document_set == "created"
      @documents = mine.paginate(:page => whitelisted[:page], :per_page => per_page).order("created_at DESC")
    elsif document_set == "all"
      if current_user.admin?
        @documents = Document.paginate(:page => whitelisted[:page], :per_page => per_page).order("created_at DESC")
      else
        @documents = shared.paginate(:page => whitelisted[:page], :per_page => per_page).order("created_at DESC")
      end
    end

    if params["search"] && params["search"] != ""
      q = params["search"].downcase

      case params["method"]
      when "title"
        @documents = myvisible.select { |d| d.title.downcase.include? q }
        @title_text = "Title: '#{params["search"]}'"
      when "author"
        @documents = myvisible.select { |d| d.author.downcase.include? q }
        @title_text = "Author: '#{params["search"]}'"
      when "status"
        @documents = myvisible.select { |d| d.state.downcase.include? q }
        @title_text = "Status: '#{params["search"]}'"
      end #end case
    end #end if
  end #end index

  # GET /documents/1
  # GET /documents/1.json
  def show
    if @document.nil?
      raise ActionController::RoutingError.new("Not Found")
    else
      if request.path != document_path(@document)
        redirect_to @document, status: :moved_permanently
      end

      # configuration for annotator
      @annotation_categories_enabled = Tenant.annotation_categories_enabled
      @enable_rich_text_editor = ENV["ANNOTATOR_RICHTEXT"]
      @tiny_mce_toolbar = ENV["ANNOTATOR_RICHTEXT_CONFIG"]

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @document }
      end
    end
  end

  # GET /documents/1/preview
  def preview
    respond_to do |format|
      format.html # preview.html.erb
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(documents_params)
    @document.user = current_user

    if params["type"]
      @document.update_attribute(:resource_type, params["type"])
    end

    #attach document to groups
    if !params[:document][:groups].nil?
      params[:document][:groups].each do |g|
        if !g.empty? and Group.find_by(id: g.to_i)
          @document.groups << Group.find_by(id: g.to_i)
        end
      end
    end

    respond_to do |format|
      if @document.save
        if params[:document][:upload].present?
          DocumentProcessor.perform_later(@document.id, @document.state, Apartment::Tenant.current)
          @document.pending!
        end

        format.html { redirect_to documents_path(docs: "created"), notice: "Document was successfully created.", anchor: "created" }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new", status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
        @document.delete
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.friendly.find(params[:id])
    @group_params = params[:document][:groups]

    #attach document to groups
    if !@group_params.nil?

      # destroy deleted groups
      @document.groups.each do |g|
        if !@group_params.include?(g.id.to_s)
          @document.groups.destroy(g)
        end
      end

      # add new groups
      @group_params.each do |g|
        if !g.empty?
          @foundgroup = Group.find_by(id: g.to_i)
          if !@foundgroup.nil? and !@document.groups.include?(@foundgroup)
            @document.groups << @foundgroup
          end
        end
      end
      if @group_params.length == 1 and @group_params[0].empty?
        @document.groups.destroy_all
      end
    end

    @document.update_attribute("updated_at", Time.now)

    respond_to do |format|
      if @document.update_attributes(documents_params)
        format.html { redirect_to documents_path(docs: "created"), notice: "Document was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    flash[:alert] = "Document " + @document.title + " was succesfully deleted."
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_path(docs: "created") }
      format.json { head :no_content }
    end
  end

  #JSON for saving state
  def set_default_state
    @document.update_attribute(:default_state, params[:default_state])

    render :json => {}
  rescue Exception => e
    render :json => {}
  end

  def archive
    respond_to do |format|
      if @document.update_attribute(:state, "archived")
        format.html { redirect_to documents_url, notice: "Document was successfully archived.", anchor: "created" }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def publish
    respond_to do |format|
      if @document.update_attribute(:state, "published")
        format.html { redirect_to documents_url, notice: "Document is now published.", anchor: "created" }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def publicize
    respond_to do |format|
      if @document.update_attribute(:state, "public")
        format.html { redirect_to documents_url, notice: "Document is now public.", anchor: "created" }
      else
        format.html { render action: "edit" }
      end
    end
  end

  #Export HTML
  def export
    send_data(@document.snapshot, filename: "#{@document.title}.html")
  end

  #Snapshot of document for export
  def snapshot
    @document.update_attribute(:snapshot, params[:snapshot])
    render :json => {}
  rescue Exception => e
    render :json => {}
  end

  # Helper which accepts an array of items and filters out those you are not allowed to read, according to CanCan abilities.
  # From Miximize.
  def filter_by_can_read(items)
    items.collect do |i|
      i unless cannot? :read, i
    end
  end

  def filter_by_samegroup(items)
    items.collect do |i|
      i unless cannot? :read, i
    end
  end

  before_action :prepare_for_mobile

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
  end

  private

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "images/#{SecureRandom.uuid}/${filename}", success_action_status: "201", acl: "public-read")
  end

  def find_document
    @document = Document.friendly.find(params.has_key?(:document_id) ? params[:document_id] : params[:id])
  end

  def documents_params
    params.require(:document).permit(:title, :state, :chapters, :text, :snapshot, :user_id, :author,
                                     :edition, :publisher, :publication_date, :source, :rights_status, :upload,
                                     :survey_link, :location, :page_numbers, :series, :journal_title, :notes,
                                     :resource_type, :groups)
  end
end

app/views/documents/_annotation_sidebar.html.erb
<%= render :partial => "shared/annotator_base" %>
<% if !@document.nil? %>
  <script type="text/javascript" charset="utf-8">
  var document_slug = "<%= @document.slug %>";
  var default_state = <%= @document.default_state.present? ? (raw @document.default_state) : (raw "''") %>;

  //testing per-group annotations
  var userGroupIds = [];
  var docGroupIds = [];

  <% current_user.groups.each do |g| %>
    userGroupIds.push(<%=g.id %>);
  <% end %>

  <% @document.groups.each do |g| %>
    docGroupIds.push(<%=g.id %>);
  <% end %>

  // get intersection of document's groups and user's groups
  var group_ids = userGroupIds.filter(value => docGroupIds.includes(value));

  var annotatorOptions = {'readOnly': <%= @document.archived? %>};
  var filter_user = "<%= current_user.email %>";
  var token = '<%= session["jwt"] %>';
  var annotation_username = "<%= current_user.first_name_last_initial %>";
  var sidebar_sort_editable = <%= current_user && current_user.has_document_permissions?(@document) %>;
  var mobile_device = <%= mobile_device? -%>;
  var search_context = 'document';
  var api_url = location.protocol+'//'+'<%= ENV["API_URL"] %>';
  var doc_uri = [location.protocol, '//', location.host, location.pathname].join('');

  var plugin_options = function() {
    return {
      <% unless current_user.has_role?(:admin) && ENV["ANNOTATOR_FILTER"] == 'true' %>
      Filter: false,
      <% end %>
      Auth: {
        token: token
      },
      Store: {
        prefix: api_url,
        annotationData: {
          'uri': doc_uri,
          'group_ids': group_ids,
          'doc_title': '<%= @document.title %>',
          'doc_author': '<%= @document.author %>',
          'doc_date': '<%= @document.publication_date %>',
          'doc_publisher': '<%= @document.publisher %>',
          'doc_edition': '<%= @document.edition %>',
          'doc_source': '<%= @document.source %>'
        },
        // loadFromSearch: annotation_studio.loadOptions({ mode: default_state[0], limit: 100 })

        //default_state is nil for all current documents so set to empty string by var @ line 5
        // changed code for now to get mode=user as default.
        loadFromSearch: annotation_studio.loadOptions({limit: 100 })

      },
      Markdown: false, // use RichText instead
      AnnotateItPermissions: false, // this is built into the kitchen sink, so cancel it
      Permissions: {
        user: "<%= current_user.email %>",
        permissions: {
          'read': ['<%= current_user.email %>'], // default: review mode; this is what users will need to control
          'update': ['<%= current_user.email %>'], // no one else can ever update
          'delete': ['<%= current_user.email %>'], // no one else can ever delete
          'admin': ['<%= current_user.email %>'] // no one else can ever admin
        },
        userString: function (user) {
          if(user && user.id){
            return user.id;
          }
          return user;
        },
        // Permissions settings per-annotation
        showViewPermissionsCheckbox: true,
        showEditPermissionsCheckbox: false
      }
      <% if Tenant.annotation_categories_enabled -%>
      , Categories: <%= raw AnnotationCategory.to_plugin_init %>
      <% end -%>
    }
  };

  jQuery(function ($) {
    // Create username for a given annotation if needed.
    <% if current_user.has_role?(:admin) %>
      $('#adminview').on('click', { mode: 'admin', id: 'adminview' }, annotation_studio.modeFilter);
    <% end %>
  });
  </script>
<% end %>

app/views/documents/_annotator-setup.html.erb
<div class="span3 hidden-phone hidden-tablet">
  <div id="annotation-well" class="affix">
    <div class="btn-group" data-toggle="buttons-radio" id="view-chooser">
      <button class="viewchoice btn btn-small active" id="userview">Mine</button>
      <button class="viewchoice btn btn-small" id="groupview">Group</button>
      <button class="viewchoice btn btn-small" id="classview">Class</button>
      <% if current_user.has_role?(:admin) %>
      <button class="viewchoice btn btn-small btn-inverse" id="adminview">All</button>
      <% end %>
    </div>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.3.3/underscore-min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/backbone.js/0.9.2/backbone-min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.4.2/mustache.min.js"></script>
    <ul id="annotation-list"></ul>
    <script type="text/template" id="comment-template">
      <span id="sb{{uuid}}" href="#full{{uuid}}" data-highlight="#hl{{uuid}}" rel="tooltip" title="{{username}}" class="highlightlink comment">{{{text}}}</span>
      <span id="quote{{uuid}}" class="sbquote details">&quot;{{{quote}}}&quot;</span>
      <span id="text{{uuid}}" class="sbtext details">{{{text}}}</span>
      <span id="info{{uuid}}" class="sbinfo details">{{username}}</span>
      <div id="tags{{uuid}}" class="sbtags details">{{#tags}}<span class="label">{{.}}</span> {{/tags}}</div>
    </script>
    <script type="text/template" id="highlight-template">
      <span id="sb{{uuid}}" data-highlight="#hl{{uuid}}" rel="tooltip" title="{{username}}" class="highlightlink highlight sbquote">&quot;{{{quote}}}&quot;</span>
      <span id="quote{{uuid}}" class="sbquote details">&quot;{{{quote}}}&quot;</span>
      <div id="tags{{uuid}}" class="sbtags details">{{#tags}}<span class="label">{{.}}</span> {{/tags}}</div>
    </script>
  </div><!--/well -->
</div><!--/span3 -->
<%= javascript_include_tag "sidebar" %>
<script type="text/javascript" charset="utf-8">
jQuery(function ($) {

  var groups = "<%= current_user.rep_group_list %>".split(/, /);
  var subgroups = "<%= current_user.rep_subgroup_list %>".split(/, /);

  // Bootstrap Backbone Sidebar //
  var sidebar = new Sidebar.App();
  Backbone.history.start({pushState: true, root: window.location});

  var options = {
    optionsAnnotator: {
      permissions: {
        user: "<%= current_user.email %>",
        permissions: {
              'read': ['<%= current_user.email %>'], // default: review mode; this is what users will need to control
              'update': ['<%= current_user.email %>'], // no one else can ever update
              'delete': ['<%= current_user.email %>'], // no one else can ever delete
              'admin': ['<%= current_user.email %>'] // no one else can ever admin
        },
        userString: function (user) {
          return user.split("@")[0]
        },
        // Permissions settings per-annotation
        showViewPermissionsCheckbox: true,
        showEditPermissionsCheckbox: false
      },
      <% if current_user.has_role?(:admin) && ENV["ANNOTATOR_FILTER"] == 'true' %>
      filter: {},
      <% end %>
      auth: {
        token: '<%= @jwt %>'
      },
      store: {
          prefix: '<%= ENV["API_URL"] %>',
          annotationData: {
              'uri': [location.protocol, '//', location.host, location.pathname].join(''),
              "groups": groups,
              "subgroups": subgroups,
              // "username": 'Jamie F.',
          },
          loadFromSearch: {
              'limit': 100,
              "groups": groups,
              "subgroups": subgroups,
              'user': "<%= current_user.email %>",
              'mode': 'user', // default mode -- user can switch via sidebar button.
              'context': 'document',
              'uri': [location.protocol, '//', location.host, location.pathname].join('')
          }
      },
      richText: {
        editor_enabled: <%= ENV["ANNOTATOR_RICHTEXT"] %>,
        tinymce: {
          toolbar: '<%= ENV["ANNOTATOR_RICHTEXT_CONFIG"] %>'
        }
      },
      annotator: {
        readOnly: <%= @document.deleted? %>
      }
    },
    optionsVideoJS: {
      techOrder: ["html5", "flash", "youtube"]
    },
    optionsRS: {},
    optionsOVA: {
      posBigNew: 'none'
    }
  }
  var studio = new OpenVideoAnnotation.Annotator($('#textcontent'), options);

  // Create a UUID for a given annotation if needed.
  // Once created, this shouldn't be changed.
  var createUuid = function(annotation) {
    if (annotation.uuid == null) {
      annotation.uuid = Math.uuid(8, 16);
      console.info("New uuid for annotation: '"+annotation.quote+"': "+ annotation.uuid);
    }
    else {
      console.info("Existing uuid for annotation: '"+annotation.quote+"': "+ annotation.uuid);
    }
  };

  // Create username for a given annotation if needed.
  var addUserName = function(annotation) {
    if (annotation.username == null) {
      annotation.username = "<%= current_user.first_name_last_initial %>";
      console.info("New username for annotation: <%= current_user.first_name_last_initial %>");
    }
  };

  // Add UUIDs to highlights so sidebar and highlights can link to one another.
  var addUuid;
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };
  addUuid = __bind(function(a) {
    if (a.highlights[0] != null) {
      a.highlights[0].id = "hl"+ a.uuid;
      a.highlights[0].title = a.user;
    }
    else {
      console.info("Err...");
    }
  }, this);

  var stopSpinner = function(){
    $('#spinnermodal').modal('hide');
  };

  var createAndAddUuid = function(annotation){
    createUuid(annotation);
    addUuid(annotation);
  };

  // Update the sidebar with local annotation data
  var loadSidebar = function(annotation) {
    setTimeout(function() {
        sidebar.listAnnotations(studio.annotator.dumpAnnotations());
    }, 100);
  };

  // Remove all comment icons and load sidebar with local data
  var deleteFromSidebar = function(annotation) {
    $(".icon-comment").remove();
    setTimeout(function() {
        sidebar.listAnnotations(studio.annotator.dumpAnnotations());
    }, 100);
  };

  var showAnnId =  function(annotation) {
    var newAnn = new Sidebar.Annotation(annotation);
    console.info(newAnn.get("uuid"));
  };

  $('#userview').on('click', { mode: 'user', id: 'userview' }, modeFilter);
  $('#groupview').on('click', { mode: 'group', id: 'groupview' }, modeFilter);
  $('#classview').on('click', { mode: 'class', id: 'classview' }, modeFilter);
  <% if current_user.has_role?(:admin) %>
  $('#adminview').on('click', { mode: 'admin', id: 'adminview' }, modeFilter);
  <% end %>

  function modeFilter(event) {
    $('.viewchoice').removeClass("active");

    $('#spinnermodal').modal('show');

    var loadOptions = {
      'limit': 1000,
      "groups": groups,
      "subgroups": subgroups,
      'user': "<%= current_user.email %>",
      'mode': event.data.mode,
      'context': 'document',
      'uri': [location.protocol, '//', location.host, location.pathname].join('')
    };

    var reload_data = reloadAnnotations(loadOptions);
    var cleanup_document = cleanupDocument();

    $.when(reload_data).then(cleanup_document).done(refreshAnnotations(), loadSidebar());
  }

  function reloadAnnotations(loadOptions) {
    var dfd = new $.Deferred();
    studio.annotator.plugins.Store.annotations = [];
    if (studio.annotator.plugins.Store.loadAnnotationsFromSearch(loadOptions)) {
      setTimeout(function() {
        dfd.resolve("Reload complete.");
      }, 100);
      console.log("Reload complete.");
    }
    else {
      console.log("Reload failed.");
      dfd.reject("Reload failed.");
    }
    return dfd.promise();
  }

  function cleanupDocument () {
    var dfd = new $.Deferred();
    if (removeHilites()) {
      console.log("Cleanup complete.");
      dfd.resolve("Cleanup complete.");
    }
    else {
      console.log("Cleanup failed.");
      dfd.reject("Cleanup failed.");
    }
    return dfd.promise();
  }

  function removeHilites() {
    $(".icon-comment").remove();
    var hilites = $('.annotator-hl');
    if (hilites.length > 0) {
      hilites.children().unwrap();
      hilites.contents().unwrap();
    }
    return true;
   }

  function refreshAnnotations() {
    studio.annotator.loadAnnotations(studio.annotator.plugins.Store.annotations);
    $('#spinnermodal').modal('hide');
  }

  var handleHash = function(annotation) {
    var hash = window.location.hash
    if (hash.length > 0){
      console.info(hash);
      setTimeout(function(){
        $('html,body').animate({scrollTop: $(hash).offset().top - 150}, 500);
      },1000);
    }
  };

  // When the annotator loads remote data, update sidebar
  studio.annotator.subscribe('annotationsLoaded', loadSidebar);
  studio.annotator.subscribe('annotationsLoaded', stopSpinner);
  studio.annotator.subscribe('annotationsLoaded', handleHash);

  // Update all highlights with UUIDs
  studio.annotator.subscribe('annotationsLoaded', __bind(function(annotations) {
    annotations.map(addUuid); // copies the UUID value from the object field to the highlight spans attribute value.
  }, this));

  // Add the UUID to the local annotation object and to the highlight span before saving
  studio.annotator.subscribe('beforeAnnotationCreated', createUuid); // creates, if need be, and adds, both to object, and to highlight.
  studio.annotator.subscribe('beforeAnnotationCreated', addUserName); // creates, if need be, and adds, both to object, and to highlight.


  // Once the local object has been created, load the sidebar from local data (already contains UUID)
  studio.annotator.subscribe('annotationCreated', loadSidebar);
  studio.annotator.subscribe('annotationCreated', addUuid);

  // When the local object is updated (contains previously created/stored UUID), load the sidebar from local data
  studio.annotator.subscribe('annotationUpdated', loadSidebar);
  studio.annotator.subscribe('annotationDeleted', deleteFromSidebar);
  $(".annotator-checkbox label").text('Allow my groups to view this annotation')

});
</script>

app/views/documents/_processed_message.html.erb
<div class="alert alert-info" id="processed_message">
  <h4>Please wait.</h4>
   The document is being converted.
</div>

app/views/documents/_snapshot_progress.html.erb
<div class="modal fade bs-example-modal-sm" id="snapshot-progress" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header"></div>
      <div class="modal-body">
        <h3>Creating Snapshot...</h3>
      </div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>

app/views/documents/_spinner_modal.html.erb
<div id="spinnermodal" class="modal" tabindex="-1" role="dialog" aria-labelledby="spinnermodallabel">
  <div class="modal-body" id="spinnerdiv"><em>Loading annotations...</em></div>
</div>

app/views/documents/_survey_button.html.erb
<% if !@document.nil? %>
<div class="alert alert-info" id="survey_button_container">
  <a href="<%= @document.survey_link %>" class="btn btn-info" target="_blank">Take the survey</a>
</div>
<% end %>

app/views/documents/edit.html.erb
<%= content_for :page_title, "Editing #{@document.title}" %>
<%= content_for :body_id, 'documents' %>
<%= content_for :body_class, 'edit' %>
<div class="panel panel-default">

  <div class="panel-heading">
    <h4 class="panel-title">Create/Edit Document</h4>
  </div>
  <div class="panel-body">
    <%= render :partial => 'form', :locals => {:create => false} %>
  </div><!--/panel-body -->

</div><!--/row -->

app/views/documents/preview.html.erb
<%= content_for :body_id, 'documents' %>
<%= content_for :body_class, 'show' %>
<%= content_for :page_title, @document.title %>
<%= stylesheet_link_tag "documents" %>
<div class="row">
  <div class="col-md-2">
  </div><!--/col-md-2 -->
  <div class="col-md-8 height-size-to-page-scroll">
    <% if ! @document.processed? %>
      <%= render 'processed_message' %>
    <% end %>
    <div id="textcontent" style="overflow-y:scroll;height:95%;margin-top:20px;">
      <div id="snapshot">
        <%= @document.snapshot.html_safe %>
      </div>
    </div>
  </div><!--/col-md-8 -->
  <div class="col-md-2" id="tool-sidebar">
    <%= link_to("Download", document_export_path(@document), class: "btn btn-default btn-sm", role: "button") %>
  </div><!--/col-md-2 -->
</div><!--/row -->
<%= render "documents/help" %>